<?php

namespace ContainerSSJr7kU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApp_Parser_Application_GetParserValueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'app.parser.application.get_parser_value' shared autowired service.
     *
     * @return \App\Parser\Application\GetParserValue
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Parser/Application/GetValueParser.php';

        return $container->services['app.parser.application.get_parser_value'] = new \App\Parser\Application\GetParserValue();
    }
}
