<?php

namespace ContainerSSJr7kU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParserCsvCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ParserCsvCommand' shared autowired service.
     *
     * @return \App\Command\ParserCsvCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ParserCsvCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Parser/Application/GetValueParser.php';

        $container->privates['App\\Command\\ParserCsvCommand'] = $instance = new \App\Command\ParserCsvCommand(($container->services['app.parser.application.get_parser_value'] ??= new \App\Parser\Application\GetParserValue()));

        $instance->setName('parser_csv');
        $instance->setDescription('Parser de archivos csv a tablas in (sucias)');

        return $instance;
    }
}
