<?php

namespace ContainerXMKJB64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParserCsvCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\ParserCsvCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\ParserCsvCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('parser_csv', [], 'Parser de archivos csv a tablas in (sucias)', false, #[\Closure(name: 'App\\Command\\ParserCsvCommand')] fn (): \App\Command\ParserCsvCommand => ($container->privates['App\\Command\\ParserCsvCommand'] ?? $container->load('getParserCsvCommandService')));
    }
}
